name: messager
description: Mitso messanger mobile app

version: 1.0.0+1

environment:
  sdk: ">=2.8.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  http: ^0.13.1
  shared_preferences: ^2.0.5
  uuid: ^3.0.1
  async: ^2.5.0
  rxdart: ^0.26.0
  socket_io_client: ^0.9.12
  wave:
    git:
      url: git://github.com/searchy2/wave.git
  provider: ^5.0.0
  mock_data: ^1.2.8
  flutter_svg: ^0.21.0-nullsafety.0
  firebase_messaging: ^9.0.0
  path_provider: ^2.0.1
  barcode_scan: ^3.0.1
  qr_flutter: ^4.0.0
  fluttertoast: ^8.0.3
  flutter_linkify: ^5.0.0
  url_launcher: any
  file_picker: any
  image_picker: ^0.7.3
  image_cropper: ^1.4.0
  firebase_core : any
  share: ^2.0.1
  sembast: ^3.0.0+4
  flare_flutter: ^2.0.6
  shimmer: ^1.1.2
  preload_page_view: ^0.1.5
  photo_view: ^0.11.1
  cached_network_image: ^3.0.0-nullsafety
  encrypt: ^5.0.0-beta.1
  agora_rtc_engine: ^3.3.2
  permission_handler: ^6.1.1
  path: ^1.8.0
  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
    - family: SFProDisplay-Bold
      fonts:
        - asset: assets/fonts/SFProDisplay-Bold.ttf

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/