name: messager
description: Mitso messanger mobile app

version: 1.0.0+1

environment:
  sdk: ">=2.8.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1
  http: ^0.12.2
  shared_preferences: ^0.5.12+2
  uuid: ^2.2.2
  async: ^2.4.2
  rxdart: ^0.24.1
  socket_io_client: ^0.9.11
  wave: ^0.1.0
  provider: ^4.3.2+2
  cached_network_image: ^2.3.3
  mock_data: ^1.2.8
  flutter_svg: ^0.19.0
  firebase_messaging: ^7.0.3
  path_provider: ^1.6.21
  barcode_scan: ^3.0.1
  qr_flutter: ^3.2.0
  fluttertoast: ^7.1.1
  flutter_local_notifications: ^2.0.1
  flutter_linkify: ^3.1.3
  url_launcher: ^5.4.10
  file_picker: ^2.0.7
  image_picker: ^0.6.7+12
  image_cropper: ^1.3.1
  esys_flutter_share: ^1.0.2
  uni_links: ^0.4.0
  sembast: ^2.4.7+7
  flare_flutter: ^2.0.6
  system_shortcuts: ^1.0.0
  shimmer: ^1.1.2
  preload_page_view: ^0.1.4
  photo_view: ^0.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
    - family: SFProDisplay-Bold
      fonts:
        - asset: assets/fonts/SFProDisplay-Bold.ttf

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/