name: messager
description: Mitso messanger mobile app

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1
  http: ^0.12.0+4
  shared_preferences: ^0.5.7
  uuid: ^2.0.4
  async: ^2.4.0
  rxdart: ^0.24.0
  socket_io_client: ^0.9.9
  wave: ^0.0.8
  provider: ^4.0.5+1
  cached_network_image: ^2.1.0+1
  mock_data: ^1.2.6
  flutter_svg: ^0.17.4
  firebase_messaging: ^6.0.13
  path_provider: ^1.6.7
  barcode_scan: ^3.0.0
  qr_flutter: ^3.2.0
  fluttertoast: ^4.0.1
  flutter_local_notifications: ^1.4.2
  flutter_linkify: ^3.1.2
  url_launcher: ^5.4.5
  file_picker: ^1.9.0
  image_cropper: ^1.2.1
  esys_flutter_share: ^1.0.2
  uni_links: ^0.2.0
  sembast: ^2.4.2
  flare_flutter: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
    - family: SFProDisplay-Bold
      fonts:
        - asset: assets/fonts/SFProDisplay-Bold.ttf

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/